name: Main
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Setup SxS dotnet
        uses: ./.github/actions/setup-sxs-dotnet
        with:
          dotnet-versions: 2.1.202, 2.1.805, 3.1.201
      - name: Test
        run: dotnet test